from random import randint

def game_mode():  # Function for selecting the game mode
    while True:
        print('''Choose your game mode!
              Enter the number 1 if you want to play with numbers from 1 to 100
              Enter the number 2 if you want to select a range of numbers yourself''')
        mode = input()
        if mode != '1' and mode != '2':
            print('Please enter the correct value!')
            continue
        else:
            return mode

def introduction_of_the_value(a, b):  # A function that takes a number and checks it for compliance with the set range
    while True:
        print(f'Enter a number between {a} and {b}')
        input_value = input()
        if input_value.isdigit() is False:
            print(f'Shall we introduce an integer from {a} to {b}?')
        elif int(input_value) not in range(a, b + 1):
            print(f'Shall we introduce an integer from {a} to {b}?')
        else:
            return int(input_value)
        
def repeat():  # A function that suggests repeating the game
    print('Would you like to replay the game?')
    print('Enter "y" if yes, "n" if no.')
    repeat_value = input()
    if repeat_value == 'y' or repeat_value == 'Y':
        game()
    elif repeat_value != 'n' and repeat_value != 'N':
        print('Please enter the correct value')
        repeat()

def game():  # The main function that checks if the entered number is correct, counting the number of tries
    if game_mode() == '1':
        a, b = 1, 100
    else:
        while True:
            a = input('Enter the left border')
            if a.isdigit() is False:
                print('Please enter the correct value - integer')
                continue
            a = int(a)
            break
        while True:
            b = input('Enter the right border. It must be larger than the left border')
            if b.isdigit() is False:
                print('Please enter a valid value - an integer greater than', a)
                continue
            if int(b) <= a:
                print('Please enter a valid value - an integer greater than', a)
                continue
            b = int(b)
            break
    correct_number = randint(a, b)
    counter = 0
    while True:
        counter += 1
        input_value = introduction_of_the_value(a, b)
        if input_value < correct_number:
            print('Your number is lower than your guess, try again.')
        elif input_value > correct_number:
            print('Your number is higher than your guess, try again.')
        else:
            print('You guessed it, congratulations!')
            print(f'The number of your attempts - {counter}')
            repeat()
            break

print('''Welcome to the number guessing game!
      This is a game in which you have to guess numbers that are generated by a computer.
      There are 2 modes of play:
      1. The computer generates numbers from 1 to 100.
      2. You choose the range of numbers yourself.''')

game()

print('Thanks for playing the number guessing game. See you later...')